    <script src="{{ asset('assets/web') }}/js/jquery.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/bootstrap.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/jquery.nice-select.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/slick.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/jquery.counterup.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/waypoints.js"></script>
    <script src="{{ asset('assets/web') }}/js/jquery.meanmenu.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/jquery.magnific-popup.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/inview.min.js"></script>
    <script src="{{ asset('assets/web') }}/js/wow.js"></script>
    <script src="{{ asset('assets/web') }}/js/tilt.jquery.js"></script>
    <script src="{{ asset('assets/web') }}/js/custom-rtl.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
